# Example workflow using Gistdex reusable workflow
# Copy this file to .github/workflows/doc-impact.yml in your repository

name: Documentation Impact Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # Optional: Only run when specific files change
    # paths:
    #   - 'src/**'
    #   - 'docs/**'
    #   - '*.md'

jobs:
  # Simple usage with defaults
  analyze-docs:
    uses: ushironoko/gistdex/.github/workflows/reusable-doc-impact.yml@main
    secrets:
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}

  # Advanced usage with custom configuration
  # analyze-docs-custom:
  #   uses: ushironoko/gistdex/.github/workflows/reusable-doc-impact.yml@main
  #   with:
  #     threshold: '0.6'  # Lower threshold for more sensitive detection
  #     doc-paths: 'docs/**/*.md,README.md,guides/**/*.md'  # Custom document paths
  #     node-version: '20'  # Use specific Node.js version
  #     gistdex-version: '1.5.0'  # Pin to specific Gistdex version
  #     post-pr-comment: true  # Post results as PR comment
  #     add-label: true  # Add label to PR
  #     label-name: 'docs-update-needed'  # Custom label name
  #   secrets:
  #     GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}